[profile.default]
solc_version   = "0.8.30"
src = "src"
out = "out"
libs = ["lib"]
via-ir=true
runs = 256         
max_test_rejects = 65536  # Prevents infinite loops when values get rejected
seed = "0x1234"    # Optional: set seed for reproducibility
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
